services:
  greeter:
    build: .
    environment: 
      - SERVICE_NAME=greeter
      - NATS=nats://nats
    depends_on:
      - nats

  blog:
    build: .
    environment: 
      - SERVICE_NAME=blog
      - NATS=nats://nats
      - MYSQL=mysql://root:mysql@db/app
    depends_on:
      nats:
        condition: service_started
      db:
        condition: service_healthy
  
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=app
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  nextjs:
    build: .
    environment: 
      - NATS=nats://nats
    ports: 
      - "3000:3000"
    command: npm run start:nextjs
    depends_on:
      - nats
      - blog
      - greeter


  nats:
    image: nats


volumes:
  db-data: